### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 503: first byte timeout

### ISSUE THREAD

**Issue by Sdoof** [fxcm/fxcmpy#15]
, I have put a very simple code to download the weekly tick data through FXMPY unfortunately the http response fail after a while, what is the fix for this?

Code:
`import gc
gc.collect()
import pandas as pd
import datetime as dt
from fxcmpy import fxcmpy_tick_data_reader as tdr

start = dt.datetime(2015, 1, 1)
# end = dt.datetime.now()
# end = dt.datetime(2018, 8, 3)
end = dt.datetime(2018, 7, 27) #WEEK 30
# symbol='EURUSD'
SYMB=tdr.get_available_symbols()
print(SYMB)
SYMB=[
'EURAUD','EURCHF','EURGBP',
'EURJPY','EURUSD','GBPCHF','GBPJPY','GBPNZD','GBPUSD','GBPCHF','GBPJPY',
'GBPNZD','NZDCAD','NZDCHF','NZDJPY','NZDUSD','USDCAD','USDCHF','USDJPY'

for symbol in SYMB:
    dr = tdr(symbol, start, end, verbosity=True)
    raw_data= dr.get_raw_data()
    linkfile_TICK = 'I://LUBUNTU_backup_APR_2018//DATA//TickDownloader//tickdata//FXCM//TICKS//WEEKLY_GITHUB//'
    _csv = '.csv'
    linkfile_data = linkfile_TICK + symbol + _csv
    pd.DataFrame(raw_data).to_csv(linkfile_data)
    del raw_data
`
Everything runs fine but after a while I get this:
**Error:**
`
Fetching data from: https://tickdata.fxcorporate.com/EURJPY/2015/4.csv.gz
Fetching data from: https://tickdata.fxcorporate.com/EURJPY/2015/5.csv.gz
Traceback (most recent call last):
  File "C:/Users/olivi/PycharmProjects/IB_FX/12c_FXCM_TICK_FXCMPY.py", line 36, in <module>
    dr = tdr(symbol, start, end, verbosity=True)
  File "C:\Users\olivi\AppData\Roaming\Python\Python36\site-packages\fxcmpy\fxcmpy_data_reader.py", line 96, in __init__
    self.__fetch_data__()
  File "C:\Users\olivi\AppData\Roaming\Python\Python36\site-packages\fxcmpy\fxcmpy_data_reader.py", line 174, in __fetch_data__
    data = self.__fetch_dataset__(url)
  File "C:\Users\olivi\AppData\Roaming\Python\Python36\site-packages\fxcmpy\fxcmpy_data_reader.py", line 185, in __fetch_dataset__
    requests = urllib.request.urlopen(url)
  File "C:\ProgramData\Anaconda3_5_2_0\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3_5_2_0\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\ProgramData\Anaconda3_5_2_0\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\ProgramData\Anaconda3_5_2_0\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\ProgramData\Anaconda3_5_2_0\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3_5_2_0\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: first byte timeout

Process finished with exit code 1
`

**Comment by Sdoof** [comment]
The range before failure is variable for instance on EURJPY there was a
failure  after only 5 weekly files and on EURCHF after only 34, so not even
a year of data. That s not logical, the load process should be consistent

*Kind regards,*
*Olivier Van Parys*
