### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by henryatman** [fxcm/fxcmpy#16]
if after running some time, alway crash and show this error, can you guys fix this ?

this is very important error, cause don't safe running and keep stable service. 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fxcmpy/fxcmpy.py", line 2377, in __connect__
    self.socket.wait()
  File "/usr/local/lib/python3.6/dist-packages/socketIO_client/__init__.py", line 251, in wait
    self._process_packets()
  File "/usr/local/lib/python3.6/dist-packages/socketIO_client/__init__.py", line 276, in _process_packets
    for engineIO_packet in self._transport.recv_packet():
  File "/usr/local/lib/python3.6/dist-packages/socketIO_client/transports.py", line 158, in recv_packet
    packet_text)
  File "/usr/local/lib/python3.6/dist-packages/socketIO_client/parsers.py", line 96, in parse_packet_text
    packet_type = int(get_character(packet_text, 0))
  File "/usr/local/lib/python3.6/dist-packages/socketIO_client/symmetries.py", line 33, in get_character
    return chr(get_byte(x, index))
  File "/usr/local/lib/python3.6/dist-packages/socketIO_client/symmetries.py", line 29, in get_byte
    return indexbytes(x, index)
IndexError: index out of range
```

**Comment by fxcm-pguz** [comment]
Hi,

This seems to be caused by SocketIO library as per [socketIO-client/issues/148](https://github.com/invisibleroads/socketIO-client/issues/148)
We will investigate a workaround that was posted in that thread.

Can you tell us how long it takes for this crash to happen ?
Thank you.

Best Regards,
Pawel

**Comment by henryatman** [comment]
hi,
crash not have same time or same period, sometime is keep more long，same time it will more short，

i check the log，just given 4 example：

Start update forex data: 2018-08-29 10:51:15, 1500
Crash at: 2018-08-29 12:33:00, 120

Start update forex data: 2018-08-29 15:57:43, 1500
Crash at: 2018-08-29 21:49:22, 120

Start update forex data: 2018-08-29 21:58:00
Crash at: 2018-08-29 22:10:00

Sync data: EUR/USD, m1, 2018-08-29 14:17:00
Crash at: 2018-08-29 22:20:00

after all， it's not very stable，if can't solve，i suggest straight use `websocket` to instead of `Socket.io`, socket.io it's not strong enough。

thanks for your reply
